version: '3'
services:
  api:
    image: edwinlll/wechat-audio-conversion:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
    volumes:
      - ./.wechat-audio-conversion.yaml:/usr/local/wechat-audio-conversion/.wechat-audio-conversion.yaml
    expose:
      - 8299
    ports:
      - 8299:8299
