version: '3'
services:
  api:
    image: edwinlll/wechat-audio-conversion:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
    volumes:
      - ./.wechat-audio-conversion.yaml:/go/src/github.com/lvzhihao/wechat-audio-conversion/.wechat-audio-conversion.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      go-wrapper run api"
    expose:
      - 8299
    ports:
      - 8299:8299
